import { ShowStyleConfig } from '../helpers/config'

export function DefaultGrafikConfig(): ShowStyleConfig['GFXTemplates'] {
	return [
		{
			VizTemplate: 'arkiv',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'arkiv',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_blank',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'direkte',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'direkte',
			VizDestination: 'viz-d-ovl',
			OutType: 'B',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'billederfra_txt',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'billederfra_txt',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'billederfra_logo',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'billederfra_logo',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident_nyhederne',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_nyhederne',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident_news',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_news',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident_tv2sport',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_tv2sport',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'tlfdirekte',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'tlfdirekte',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'topt',
			SourceLayer: 'studio0_graphicsTop',
			LayerMapping: 'graphic_overlay_topt',
			INewsCode: '#kg',
			INewsName: 'topt',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'tlftopt',
			SourceLayer: 'studio0_graphicsTop',
			LayerMapping: 'graphic_overlay_topt',
			INewsCode: '#kg',
			INewsName: 'tlftopt',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'tlftoptlive',
			SourceLayer: 'studio0_graphicsTop',
			LayerMapping: 'graphic_overlay_topt',
			INewsCode: '#kg',
			INewsName: 'tlftoptlive',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'bund',
			SourceLayer: 'studio0_graphicsLower',
			LayerMapping: 'graphic_overlay_lower',
			INewsCode: '#kg',
			INewsName: 'bund',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'vaerter',
			SourceLayer: 'studio0_graphicsLower',
			LayerMapping: 'graphic_overlay_lower',
			INewsCode: '#kg',
			INewsName: 'vaerter',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'vo',
			SourceLayer: 'studio0_graphicsHeadline',
			LayerMapping: 'graphic_overlay_headline',
			INewsCode: 'DIGI=',
			INewsName: 'vo',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'trompet',
			SourceLayer: 'studio0_graphicsHeadline',
			LayerMapping: 'graphic_overlay_headline',
			INewsCode: 'DIGI=',
			INewsName: 'trompet',
			VizDestination: 'viz-d-ovl',
			OutType: 'B',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'bund_right',
			SourceLayer: 'studio0_graphicsTema',
			LayerMapping: 'graphic_overlay_tema',
			INewsCode: 'KG=',
			INewsName: 'bundright',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'TEMA_Default',
			SourceLayer: 'studio0_graphicsTema',
			LayerMapping: 'graphic_overlay_tema',
			INewsCode: 'KG=',
			INewsName: 'TEMA_default',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'TEMA_UPDATE',
			SourceLayer: 'studio0_graphicsTema',
			LayerMapping: 'graphic_overlay_tema',
			INewsCode: 'KG=',
			INewsName: 'TEMA_UPDATE',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'DESIGN_AFTERAAR_CYKEL',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_AFTERAAR_CYKEL',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_HANDBOLD',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_HANDBOLD',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_ISHOCKEY',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ISHOCKEY',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_KONTRA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_KONTRA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_NBA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_NBA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_SPORTS_LAB',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_SPORTS_LAB',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_WTA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_WTA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_VUELTA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_VUELTA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_VM',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_VM',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_WIMBLEDON',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_WIMBLEDON',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_TDF',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ESPORT',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_ESPORT',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ESPORT',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'altud',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: '#kg',
			INewsName: 'altud',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'altud',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: '#kg',
			INewsName: 'ovl-all-out',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'DESIGN_FODBOLD_20',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_FODBOLD_20',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'OUT_TEMA_H',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: '#kg',
			INewsName: 'temaud',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'DESIGN_ATP',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ATP',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'altud',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: 'KG',
			INewsName: 'ovl-all-out',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_wall_graphics',
			LayerMapping: 'graphic_wall',
			INewsCode: 'SS',
			INewsName: 'sc-stills',
			VizDestination: 'WALL1',
			OutType: 'O',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'SN_S4_LOOP_CLEAN',
			SourceLayer: 'studio0_wall_graphics',
			LayerMapping: 'graphic_wall',
			INewsCode: 'SS',
			INewsName: 'sc_loop_clean',
			VizDestination: 'WALL1',
			OutType: 'O',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'SC_LOOP_ON',
			SourceLayer: 'studio0_wall_graphics',
			LayerMapping: 'graphic_wall',
			INewsCode: 'SS',
			INewsName: 'sc-loop',
			VizDestination: 'WALL1',
			OutType: 'O',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_pilot',
			LayerMapping: 'graphic_pilot',
			INewsCode: 'GRAFIK',
			INewsName: 'FULL',
			VizDestination: 'FULL1',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'arkiv',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'arkiv',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_blank',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'direkte',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'direkte',
			VizDestination: 'viz-d-ovl',
			OutType: 'B',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'billederfra_txt',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'billederfra_txt',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'billederfra_logo',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'billederfra_logo',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident_nyhederne',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_nyhederne',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident_news',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_news',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'ident_tv2sport',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'ident_tv2sport',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'tlfdirekte',
			SourceLayer: 'studio0_graphicsIdent',
			LayerMapping: 'graphic_overlay_ident',
			INewsCode: '#kg',
			INewsName: 'tlfdirekte',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'topt',
			SourceLayer: 'studio0_graphicsTop',
			LayerMapping: 'graphic_overlay_topt',
			INewsCode: '#kg',
			INewsName: 'topt',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'tlftopt',
			SourceLayer: 'studio0_graphicsTop',
			LayerMapping: 'graphic_overlay_topt',
			INewsCode: '#kg',
			INewsName: 'tlftopt',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'tlftoptlive',
			SourceLayer: 'studio0_graphicsTop',
			LayerMapping: 'graphic_overlay_topt',
			INewsCode: '#kg',
			INewsName: 'tlftoptlive',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'bund',
			SourceLayer: 'studio0_graphicsLower',
			LayerMapping: 'graphic_overlay_lower',
			INewsCode: '#kg',
			INewsName: 'bund',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'vaerter',
			SourceLayer: 'studio0_graphicsLower',
			LayerMapping: 'graphic_overlay_lower',
			INewsCode: '#kg',
			INewsName: 'vaerter',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'vo',
			SourceLayer: 'studio0_graphicsHeadline',
			LayerMapping: 'graphic_overlay_headline',
			INewsCode: 'DIGI=',
			INewsName: 'vo',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'trompet',
			SourceLayer: 'studio0_graphicsHeadline',
			LayerMapping: 'graphic_overlay_headline',
			INewsCode: 'DIGI=',
			INewsName: 'trompet',
			VizDestination: 'viz-d-ovl',
			OutType: 'B',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'bund_right',
			SourceLayer: 'studio0_graphicsTema',
			LayerMapping: 'graphic_overlay_tema',
			INewsCode: 'KG=',
			INewsName: 'bundright',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'TEMA_Default',
			SourceLayer: 'studio0_graphicsTema',
			LayerMapping: 'graphic_overlay_tema',
			INewsCode: 'KG=',
			INewsName: 'TEMA_default',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'TEMA_UPDATE',
			SourceLayer: 'studio0_graphicsTema',
			LayerMapping: 'graphic_overlay_tema',
			INewsCode: 'KG=',
			INewsName: 'TEMA_UPDATE',
			VizDestination: 'viz-d-ovl',
			OutType: 'S',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'DESIGN_AFTERAAR_CYKEL',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_AFTERAAR_CYKEL',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_HANDBOLD',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_HANDBOLD',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_ISHOCKEY',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ISHOCKEY',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_KONTRA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_KONTRA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_NBA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_NBA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_SPORTS_LAB',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_SPORTS_LAB',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_WTA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_WTA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_VUELTA',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_VUELTA',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_VM',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_VM',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_WIMBLEDON',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_WIMBLEDON',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_TDF',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ESPORT',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_ESPORT',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ESPORT',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'altud',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: '#kg',
			INewsName: 'altud',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'altud',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: '#kg',
			INewsName: 'ovl-all-out',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'DESIGN_FODBOLD_20',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_FODBOLD_20',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'DESIGN_FODBOLD',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: 'KG=',
			INewsName: 'DESIGN_FODBOLD',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'OUT_TEMA_H',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: '#kg',
			INewsName: 'temaud',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'DESIGN_ATP',
			SourceLayer: 'studio0_design',
			LayerMapping: 'graphic_design',
			INewsCode: '#kg',
			INewsName: 'DESIGN_ATP',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: true
		},
		{
			VizTemplate: 'altud',
			SourceLayer: '',
			LayerMapping: '',
			INewsCode: 'KG',
			INewsName: 'ovl-all-out',
			VizDestination: 'viz-d-ovl',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_wall_graphics',
			LayerMapping: 'graphic_wall',
			INewsCode: 'SS',
			INewsName: 'sc-stills',
			VizDestination: 'WALL1',
			OutType: 'O',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_wall_graphics',
			LayerMapping: 'graphic_wall',
			INewsCode: 'SS',
			INewsName: '3-SPORTSDIGI',
			VizDestination: 'WALL1',
			OutType: 'O',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'SN_S4_LOOP_CLEAN',
			SourceLayer: 'studio0_wall_graphics',
			LayerMapping: 'graphic_wall',
			INewsCode: 'SS',
			INewsName: 'sc_loop_clean',
			VizDestination: 'WALL1',
			OutType: 'O',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_pilot',
			LayerMapping: 'graphic_pilot',
			INewsCode: 'GRAFIK',
			INewsName: 'FULL',
			VizDestination: 'FULL1',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_pilot',
			LayerMapping: 'graphic_pilot',
			INewsCode: 'GRAFIK',
			INewsName: 'WALL',
			VizDestination: 'WALL1',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_pilot',
			LayerMapping: 'graphic_pilot',
			INewsCode: 'GRAFIK',
			INewsName: 'OVL',
			VizDestination: 'OVL1',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_pilot',
			LayerMapping: 'graphic_pilot',
			INewsCode: '#kg',
			INewsName: 'MERGE',
			VizDestination: 'OVL1',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		},
		{
			VizTemplate: 'VCP',
			SourceLayer: 'studio0_pilot',
			LayerMapping: 'graphic_pilot',
			INewsCode: 'VIZ',
			INewsName: 'MERGE',
			VizDestination: 'OVL1',
			OutType: '',
			Argument1: '',
			Argument2: '',
			IsDesign: false
		}
	]
}
