export const DEFAULT_GRAPHICS = [
	{
		_id: 'JWq2tc7JPqrTaNgge',
		INewsCode: '#kg',
		INewsName: 'arkiv',
		VizTemplate: 'arkiv',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: 'BWxCppKQz3q6b67Z4',
		INewsCode: '#kg',
		INewsName: 'ident_blank',
		VizTemplate: 'ident',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: '5723tFYNafb9MzvzB',
		INewsCode: '#kg',
		INewsName: 'direkte',
		VizTemplate: 'direkte',
		VizDestination: 'OVL1',
		OutType: 'B',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: 'WxM8ES6kH22csjZ3W',
		INewsCode: '#kg',
		INewsName: 'billederfra_logo',
		VizTemplate: 'billederfra_logo',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: '7NXe6tKiotLueo7bF',
		INewsCode: '#kg',
		INewsName: 'ident_nyhederne',
		VizTemplate: 'ident_nyhederne',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: 'LAK5AxmHHX8ZqtASs',
		INewsCode: '#kg',
		INewsName: 'ident_news',
		VizTemplate: 'ident_news',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: 'qJSFtEybfeDdC6SW6',
		INewsCode: '#kg',
		INewsName: 'ident_tv2sport',
		VizTemplate: 'ident_tv2sport',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: 'FEDo9ywYGsr59ACFR',
		INewsCode: '#kg',
		INewsName: 'tlfdirekte',
		VizTemplate: 'tlfdirekte',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: 'L9ippawJeBAQyctnZ',
		INewsCode: '#kg',
		INewsName: 'topt',
		VizTemplate: 'topt',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsTop',
		LayerMapping: 'graphic_overlay_topt'
	},
	{
		_id: 'dumx2LeJ3jpZ9adCq',
		INewsCode: '#kg',
		INewsName: 'tlftopt',
		VizTemplate: 'tlftopt',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsTop',
		LayerMapping: 'graphic_overlay_topt'
	},
	{
		_id: 'oSGTyqkvHwLHuvue4',
		INewsCode: '#kg',
		INewsName: 'tlftoptlive',
		VizTemplate: 'tlftoptlive',
		VizDestination: 'OVL1',
		OutType: 'S',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsTop',
		LayerMapping: 'graphic_overlay_topt'
	},
	{
		_id: 'GQgCZRu7CScrgQqwM',
		INewsCode: '#kg',
		INewsName: 'bund',
		VizTemplate: 'bund',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsLower',
		LayerMapping: 'graphic_overlay_lower'
	},
	{
		_id: '2wsQGsK7KtzyqtMAm',
		INewsCode: '#kg',
		INewsName: 'vaerter',
		VizTemplate: 'vaerter',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsLower',
		LayerMapping: 'graphic_overlay_lower'
	},
	{
		_id: 'dyHaroFxb6XS9g2mY',
		INewsCode: 'DIGI=',
		INewsName: 'vo',
		VizTemplate: 'vo',
		VizDestination: 'OVL1',
		OutType: 'S',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsHeadline',
		LayerMapping: 'graphic_overlay_headline'
	},
	{
		_id: 'dFhqxiDNRYtYMsKu8',
		INewsCode: 'DIGI=',
		INewsName: 'trompet',
		VizTemplate: 'trompet',
		VizDestination: 'OVL1',
		OutType: 'B',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsHeadline',
		LayerMapping: 'graphic_overlay_headline'
	},
	{
		_id: 'Q2GPQtzF5f5ncrwus',
		INewsCode: 'KG=',
		INewsName: 'bundright',
		VizTemplate: 'bund_right',
		VizDestination: 'OVL1',
		OutType: 'S',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsTema',
		LayerMapping: 'graphic_overlay_tema'
	},
	{
		_id: 'jBCynErkKJKbS8zjq',
		INewsCode: 'KG=',
		INewsName: 'TEMA_default',
		VizTemplate: 'TEMA_Default',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsTema',
		LayerMapping: 'graphic_overlay_tema'
	},
	{
		_id: 'LqHS3JX76bK9yLFST',
		INewsCode: 'KG=',
		INewsName: 'TEMA_UPDATE',
		VizTemplate: 'TEMA_UPDATE',
		VizDestination: 'OVL1',
		OutType: 'S',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsTema',
		LayerMapping: 'graphic_overlay_tema'
	},
	{
		_id: 'EQB6r9FvuRDChsW3x',
		INewsCode: '#kg',
		INewsName: 'DESIGN_AFTERAAR_CYKEL',
		VizTemplate: 'DESIGN_AFTERAAR_CYKEL',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'p7CrFa48C67KfHkCW',
		INewsCode: '#kg',
		INewsName: 'DESIGN_HANDBOLD',
		VizTemplate: 'DESIGN_HANDBOLD',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'QWnBaKGm8p2KRzpiC',
		INewsCode: '#kg',
		INewsName: 'DESIGN_ISHOCKEY',
		VizTemplate: 'DESIGN_ISHOCKEY',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'KL87EN8DH7jXwm9wd',
		INewsCode: '#kg',
		INewsName: 'DESIGN_KONTRA',
		VizTemplate: 'DESIGN_KONTRA',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: '5ujwWuZYZbBBnoJny',
		INewsCode: '#kg',
		INewsName: 'DESIGN_NBA',
		VizTemplate: 'DESIGN_NBA',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'qNQ4pBpNinDRm9feH',
		INewsCode: '#kg',
		INewsName: 'DESIGN_SPORTS_LAB',
		VizTemplate: 'DESIGN_SPORTS_LAB',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'vGtywWoCHXsF5wBw9',
		INewsCode: '#kg',
		INewsName: 'DESIGN_WTA',
		VizTemplate: 'DESIGN_WTA',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'MCL4jaP5NTesKJsAL',
		INewsCode: '#kg',
		INewsName: 'DESIGN_VUELTA',
		VizTemplate: 'DESIGN_VUELTA',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'CF6hgcbRcxXuNdQnZ',
		INewsCode: '#kg',
		INewsName: 'DESIGN_VM',
		VizTemplate: 'DESIGN_VM',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'm9ymx2Z9wBodDaeyg',
		INewsCode: '#kg',
		INewsName: 'DESIGN_WIMBLEDON',
		VizTemplate: 'DESIGN_WIMBLEDON',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'ARceY2KjwMKJ5RMxj',
		INewsCode: '#kg',
		INewsName: 'DESIGN_TDF',
		VizTemplate: 'DESIGN_TDF',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'P4qhwcDcKLLuZZpgM',
		INewsCode: '#kg',
		INewsName: 'DESIGN_ESPORT',
		VizTemplate: 'DESIGN_ESPORT',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'XjTuv9G6hi9LyPyw6',
		INewsCode: '#kg',
		INewsName: 'altud',
		VizTemplate: 'altud',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: '',
		LayerMapping: ''
	},
	{
		_id: 'PPXH2iTLb5HdRDG9Z',
		INewsCode: '#kg',
		INewsName: 'ovl-all-out',
		VizTemplate: 'altud',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: '',
		LayerMapping: ''
	},
	{
		_id: 'QJB3rgocpkzZE2xwT',
		INewsCode: '#kg',
		INewsName: 'DESIGN_FODBOLD_20',
		VizTemplate: 'DESIGN_FODBOLD_20',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'Jba6tmeLicDeBm3mA',
		INewsCode: '#kg',
		INewsName: 'temaud',
		VizTemplate: 'OUT_TEMA_H',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: '',
		LayerMapping: ''
	},
	{
		_id: 'hWHoqk52ju5AJmuty',
		INewsCode: '#kg',
		INewsName: 'DESIGN_ATP',
		VizTemplate: 'DESIGN_ATP',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'FjwSKoh2BazojAgn2',
		INewsCode: 'KG',
		INewsName: 'ovl-all-out',
		VizTemplate: 'altud',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: '',
		LayerMapping: ''
	},
	{
		_id: '5sK4j9pZ27QCp8wFi',
		INewsCode: '#kg',
		INewsName: 'ident_play',
		VizTemplate: 'ident_play',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	},
	{
		_id: 'WR2PtzcMTdXp3Mwwi',
		INewsCode: 'SS',
		INewsName: 'sc-stills',
		VizTemplate: 'VCP',
		VizDestination: 'WALL1',
		OutType: 'O',
		IsDesign: false,
		SourceLayer: 'studio0_wall_graphics',
		LayerMapping: 'graphic_wall'
	},
	{
		_id: 'PvExvx8NqY4jWHHLQ',
		INewsCode: 'SS',
		INewsName: 'sc-loop',
		VizTemplate: 'SC_LOOP_ON',
		VizDestination: 'WALL1',
		OutType: 'O',
		IsDesign: false,
		SourceLayer: 'studio0_wall_graphics',
		LayerMapping: 'graphic_wall'
	},
	{
		_id: '7mb36fjHho2PrXcmh',
		INewsCode: 'SS',
		INewsName: 'sc_loop_clean',
		VizTemplate: 'SN_S4_LOOP_CLEAN',
		VizDestination: 'WALL1',
		OutType: 'O',
		IsDesign: false,
		SourceLayer: 'studio0_wall_graphics',
		LayerMapping: 'graphic_wall'
	},
	{
		_id: '7shXt3LpqeaZafzT7',
		INewsCode: 'GRAFIK',
		INewsName: 'FULL',
		VizTemplate: 'VCP',
		VizDestination: 'FULL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: '',
		LayerMapping: ''
	},
	{
		_id: 'Nmt46Xij6Gj8nDWL5',
		INewsCode: '#kg',
		INewsName: 'DESIGN_X_GAMES',
		VizTemplate: 'DESIGN_X_GAMES',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'zZcwo8Z8o2rd4Avxy',
		INewsCode: '#kg',
		INewsName: 'DESIGN_SC',
		VizTemplate: 'DESIGN_SC',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: true,
		SourceLayer: 'studio0_design',
		LayerMapping: 'graphic_design'
	},
	{
		_id: 'sxXgzAmyEnikFcnQ8',
		INewsCode: '#kg',
		INewsName: 'ident_BILLEDER_FRA',
		VizTemplate: 'billederfra_txt',
		VizDestination: 'OVL1',
		OutType: '',
		IsDesign: false,
		SourceLayer: 'studio0_graphicsIdent',
		LayerMapping: 'graphic_overlay_ident'
	}
]
