import { ISourceLayer, SourceLayerType } from 'tv-automation-sofie-blueprints-integration'
import { literal } from '../../common/util'
import { SourceLayer } from '../layers'

// OVERLAY group
const OVERLAY: ISourceLayer[] = [
	{
		_id: SourceLayer.PgmGraphicsIdent,
		_rank: 10,
		name: 'Ident',
		abbreviation: 'G',
		type: SourceLayerType.GRAPHICS,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: 'q,alt+a',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmGraphicsTop,
		_rank: 20,
		name: 'Top',
		abbreviation: 'G',
		type: SourceLayerType.GRAPHICS,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: 'q,alt+s',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: true,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmGraphicsLower,
		_rank: 30,
		name: 'Bund',
		abbreviation: 'G',
		type: SourceLayerType.GRAPHICS,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: 'a,s,d,f,g',
		clearKeyboardHotkey: 'q,alt+d',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: true,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmGraphicsHeadline,
		_rank: 40,
		name: 'Headline',
		abbreviation: 'G',
		type: SourceLayerType.GRAPHICS,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: 'q,alt+f',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: true,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmGraphicsTema,
		_rank: 50,
		name: 'Tema',
		abbreviation: 'G',
		type: SourceLayerType.GRAPHICS,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: 'q,alt+g',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: true,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	}
]

// JINGLE group
const JINGLE: ISourceLayer[] = [
	{
		_id: SourceLayer.PgmJingle,
		_rank: 10,
		name: 'Jingle',
		abbreviation: '',
		type: SourceLayerType.TRANSITION,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	}
]

// PGM group
const PGM: ISourceLayer[] = [
	{
		_id: SourceLayer.PgmCam,
		_rank: 0,
		name: 'Kam',
		abbreviation: 'K',
		type: SourceLayerType.CAMERA,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: 'f1,f2,f3,f4,f5,alt+f1,alt+f2,alt+f3,alt+f4,alt+f5',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: true,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmLive, // @todo: should queue by default
		_rank: 0,
		name: 'Live',
		abbreviation: 'L',
		type: SourceLayerType.REMOTE,
		exclusiveGroup: 'me1',
		isRemoteInput: true,
		isGuestInput: false,
		activateKeyboardHotkeys: '1,2,3,4,5,6,7,8,9,0',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: true,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmDVE, // @todo: should queue by default
		_rank: 0,
		name: 'DVE',
		abbreviation: 'D',
		type: SourceLayerType.SPLITS,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: 'f10',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmDVEAdlib, // @todo: should queue by default
		_rank: 0,
		name: 'DVE',
		abbreviation: 'D',
		type: SourceLayerType.SPLITS,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmDVEBox1,
		_rank: 0,
		name: 'DVE INP1',
		abbreviation: 'DB1',
		type: SourceLayerType.UNKNOWN,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmDVEBox2,
		_rank: 0,
		name: 'DVE INP2',
		abbreviation: 'DB2',
		type: SourceLayerType.UNKNOWN,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmDVEBox3,
		_rank: 0,
		name: 'DVE INP3',
		abbreviation: 'DB3',
		type: SourceLayerType.UNKNOWN,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmServer,
		_rank: 0,
		name: 'Server',
		abbreviation: 'S',
		type: SourceLayerType.VT,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmVoiceOver,
		_rank: 0,
		name: 'Voice Over',
		abbreviation: 'VO',
		type: SourceLayerType.LIVE_SPEAK,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmPilot,
		_rank: 0,
		name: 'Full',
		abbreviation: 'F',
		type: SourceLayerType.GRAPHICS,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmGraphicsTLF,
		_rank: 0,
		name: 'Telefon',
		abbreviation: 'TLF',
		type: SourceLayerType.GRAPHICS,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: 'i',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: true,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmDelayed,
		_rank: 0,
		name: 'EVS',
		abbreviation: 'EVS',
		type: SourceLayerType.VT,
		exclusiveGroup: 'me1',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: 'e',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: true,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: true,
		unlimited: false,
		onPGMClean: false
	}
]

// MUSIK group
const MUSIK: ISourceLayer[] = [
	{
		_id: SourceLayer.PgmAudioBed,
		_rank: 30,
		name: 'Audio bed',
		abbreviation: 'VO',
		type: SourceLayerType.AUDIO,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: 'plus',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	}
]
// MANUS group
const MANUS: ISourceLayer[] = [
	// {
	// 	_id: SourceLayer.PgmSlutord,
	// 	_rank: 10,
	// 	name: 'Slutord',
	// 	abbreviation: '',
	// 	type: SourceLayerType.SCRIPT,
	// 	exclusiveGroup: '',
	// 	isRemoteInput: false,
	// 	isGuestInput: false,
	// 	activateKeyboardHotkeys: '',
	// 	clearKeyboardHotkey: '',
	// 	assignHotkeysToGlobalAdlibs: false,
	// 	isSticky: false,
	// 	activateStickyKeyboardHotkey: '',
	// 	isQueueable: false,
	// 	isHidden: false,
	// 	allowDisable: false,
	// 	onPresenterScreen: false,
	// 	unlimited: false,
	// 	onPGMClean: false
	// },
	{
		_id: SourceLayer.PgmScript,
		_rank: 20,
		name: 'Manus',
		abbreviation: '',
		type: SourceLayerType.SCRIPT,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	}
]

// SEC group
const SEC: ISourceLayer[] = [
	{
		_id: SourceLayer.PgmAdlibVizCmd,
		_rank: 10,
		name: 'Viz Full',
		abbreviation: '',
		type: SourceLayerType.UNKNOWN,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '-,space',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: true,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	},
	{
		_id: SourceLayer.PgmDSK,
		_rank: 20,
		name: 'DSK off',
		abbreviation: '',
		type: SourceLayerType.UNKNOWN,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	}
]

// AUX group
const AUX: ISourceLayer[] = [
	{
		_id: SourceLayer.VizFullIn1,
		_rank: 10,
		name: 'Viz Full',
		abbreviation: '',
		type: SourceLayerType.UNKNOWN,
		exclusiveGroup: '',
		isRemoteInput: false,
		isGuestInput: false,
		activateKeyboardHotkeys: '',
		clearKeyboardHotkey: '',
		assignHotkeysToGlobalAdlibs: false,
		isSticky: false,
		activateStickyKeyboardHotkey: '',
		isQueueable: false,
		isHidden: false,
		allowDisable: false,
		onPresenterScreen: false,
		unlimited: false,
		onPGMClean: false
	}
]

export default literal<ISourceLayer[]>([...OVERLAY, ...JINGLE, ...PGM, ...MUSIK, ...MANUS, ...SEC, ...AUX])
